// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteTask(ctx context.Context, id int32) (*Task, error)
	CountTasks(ctx context.Context) (int64, error)
	CountTasksByStatus(ctx context.Context, completed pgtype.Bool) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (*Task, error)
	DeleteTask(ctx context.Context, id int32) error
	GetTask(ctx context.Context, id int32) (*Task, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]*Task, error)
	ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]*Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (*Task, error)
}

var _ Querier = (*Queries)(nil)
